### PR TITLE
Use video tag for filesmanager videos

### PR DESCRIPTION
**Pull request by SpaYco**

### CODE REVIEW

**Review by NicholasJarr — COMMENTED** [review]
@SpaYco

I tested this and it's working as expected. I just have one question. What if the user clicks the **Insert media** button and uses a URL to a `.mp4` hosted in his own site, for example. Does it add it as an `iframe` or a `video`?

**Comment by SpaYco** [comment]
@NicholasJarr I added regex for external URLs with `ogg`, `mp4`, and `webm` as those are the ones `<video>` tag will support, we also probably need to not include all video types from files manager to this tag as it won't work, but that would be on a separate PR from HJ repo.

this is the result when I add an external video link
image

**Comment by NicholasJarr** [comment]
> @NicholasJarr I added regex for external URLs with `ogg`, `mp4`, and `webm` as those are the ones `<video>` tag will support, we also probably need to not include all video types from files manager to this tag as it won't work, but that would be on a separate PR from HJ repo.

I'm not sure I get this. Can you explain it more?

> this is the result when I add an external video link

Looks good. Just a question. Did you check the source if it was really a `<video>`? It probably is. Just to be sure that everything is good 👍🏻.

**Review by NicholasJarr — APPROVED** [review]
Looks good. Just some questions on the comment above.

**Comment by SpaYco** [comment]
> I'm not sure I get this. Can you explain it more?

We use the embedMedia command when upload type is "video", but we should probably link them instead if they are not an `ogg`, `mp4`, or `webm`

> Looks good. Just a question. Did you check the source if it was really a <video>? It probably is. Just to be sure that everything is good 👍🏻.

Yes

**Pull request merged**
