### PR TITLE
[sc-845] Allow link elements to have classes

### PR DESCRIPTION
**Pull request by NicholasJarr**
## Describe the changes in this pull request

The current version doesn't allow HTML classes to be added to links.

This PR changes the editor to allow that.

#### Before

https://user-images.githubusercontent.com/28270050/196528419-32761310-3f76-434e-ba3d-a0529222b62e.mp4

#### After

https://user-images.githubusercontent.com/28270050/196528427-6abe9872-b74d-4255-8710-5fe3283f9be8.mp4

### Does this resolve an existing issue?

[sc-845] 

### How should this be tested during the review?

1. Open `/packages/ckeditor5-build-helpjuice/sample/index.html`.
2. Add a link.
3. Open the **Source** view.
4. Add an HTML class to it.

On **helpjuice-build**, it removes the `class` attribute.

On **this PR**, it allows the `class` attribute.

### CODE REVIEW

**Comment by NicholasJarr** [comment]
An alternative implementation for this would be something similar to what is in this section in [CKEditor docs](https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html#enabling-all-html-features).

We could allow custom `style` and `custom` attributes on all elements.

@SpaYco, any thoughts?

**Comment by SpaYco** [comment]
@NicholasJarr I think allowing all elements to do so would be better, afaik that's what froala is doing, and it can be helpful to customers to have more flexible customization, we can check with the customization team before we do that, so we know if it's necessary.

**Comment by SpaYco** [comment]
The only downside I can see is it can make articles body larger for those that paste a lot of stuff, which can increase page load, for some articles, while it's not necessary our fault if that happens, it would be great if we prevent it.

**Comment by NicholasJarr** [comment]
I'm closing this since #14 fixes this issue.

**Pull request closed without merging**
