### PR TITLE
[Editor] [sc-2100] [Improvement] Add option to insert PDF preview directly in the Article Editor

### PR DESCRIPTION
**Pull request by NicholasJarr**
## Describe the changes in this pull request

This PR adds a new component to the editor: `EmbeddedIFrame`. It will be used when PDFs are inserted from the Files Manager. It shows the URL preview, allows the user to resize it, and it allows the user to transform it to a link.

App PR: https://github.com/hajrice/helpjuice4/pull/2981

### Demo:

https://github.com/Helpjuice/ckeditor5/assets/28270050/0ad14a22-bb0f-4a8a-893b-8c65faab267a

### Does this resolve an existing issue?

[[sc-2100](https://app.shortcut.com/helpjuice/story/2100)]

### How should this be tested during the review?

Try to insert the following HTML through the source editor on the editor preview:

```
<iframe style="height:500px;width:100%;" src="https://s3.amazonaws.com/helpjuice-dev/helpjuice_development/uploads/upload/image/14128/2692701/1685014732996-1684737927841-sample.pdf" frameborder="0" data-embedded-iframe="true"></iframe>
```

The editor parses it and shows the `<iframe>`. If the iframe is selected, a toolbar appears with inputs for specifying the height and width, and a button that transforms the `<iframe>` to a link (if you click it and wants to go back to an `<iframe>` press `Ctrl+Z`).

### CODE REVIEW

**Comment by NicholasJarr** [comment]
I'm still making the final touches and fixing a bug (arrow keys aren't working on the dimensions inputs), but it's mostly ready. Feel free to review it.

**Comment by NicholasJarr** [comment]
It's running on staging, so feel free to test it there 👍🏻

**Review by diego-aslz — APPROVED** [review]
Nicholas, to be honest I'm not familiar with the CK editor. I glanced over the code and I'm kinda just trusting you here. Do let me know if you want me to double check you on any specific aspect of this.

**Comment by NicholasJarr** [comment]
> I'm still making the final touches and fixing a bug (arrow keys aren't working on the dimensions inputs), but it's mostly ready. Feel free to review it.

I fixed the arrow keys bug. It should be working now.

> It's running on staging, so feel free to test it there 👍🏻

The editor had to be replaced there to test another PR (https://github.com/hajrice/helpjuice4/pull/2995). We can add the changes from this PR after we're done with that one.

**Pull request merged**
