### PR TITLE
Added option to include hex colors to font color and font background …

### PR DESCRIPTION
**Pull request by chille1987**
Override font plugin and added the ability to apply hex colors to font color and font background color.

Screenshot of the feature:
CleanShot 2022-07-19 at 14 16 02@2x

See it in action:

https://user-images.githubusercontent.com/26412265/179749596-91764913-7592-419d-8ee0-d2a9ec40eec3.mp4

### CODE REVIEW

**Comment by NicholasJarr** [comment]
@chille1987

I tested it, and it worked correctly. I have some suggestions:

1. Pressing enter should apply the color.
2. Do we need to copy the whole code for the font plugin to expand it with this feature? From what I checked, most of the changes are on the view (`ColorUI`, `ColorTableView`, etc.), right? Can't we make a custom plugin, that uses the same commands as the regular font color plugin, but with a different view that has the input for custom colors? I'm suggesting this because it will not be easy to maintain this in the future if, for example, there are bug fixes on the regular font plugins.

**Comment by chille1987** [comment]
> 

We could easily create a plugin that will handle hex codes but I'm not sure how good the idea is to have two views for applying a color and background color. Instead of two icons [font-color, font-background-color] we would have [font-color, font-hex-color, font-background-color, font-hex-background-color]. In terms of updating the plugin we didn't change much of the code so I guess it should be easy to apply the changes to new plugin but yeah it will require some work.

**Comment by SpaYco** [comment]
I'm getting this error, am I doing something wrong?
image

**Comment by chille1987** [comment]
> I'm getting this error, am I doing something wrong? image

@SpaYco I can't reproduce it. Is there any steps on how to reproduce it? @NicholasJarr Can you check on your side?

**Comment by SpaYco** [comment]
@chille1987 I'm running the build with webpack dev mode and using this HTML to run it:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div id="editor" styl="height: 80vg;">
    <p>Test</p>
  </div>


  <script src="./ckeditor5/packages/ckeditor5-build-helpjuice/build/hjeditor.js" />No Script</script>
  <script>
    HelpjuiceEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>
</body>
</html>
```

**Review by NicholasJarr — APPROVED** [review]

**Comment by NicholasJarr** [comment]
@SpaYco

Can you access this file and try to use the feature: `packages/ckeditor5-build-helpjuice/sample/index.html`? It works without errors for me. The scripts on this file have more setup code than the HTML you tried to use.

**Comment by SpaYco** [comment]
> @SpaYco
> 
> Can you access this file and try to use the feature: `packages/ckeditor5-build-helpjuice/sample/index.html`? It works without errors for me. The scripts on this file have more setup code than the HTML you tried to use.

Thank you, will do.

**Pull request merged**
